name: hello-world

on: push

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - run: echo "$(cat hellow_world.txt)"
